apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-config
  namespace: flux-system
data:
  ## The Following are required by ClusterTool and CANNOT be removed
  # Ensure VIP is different from all master IPs
  VIP: 192.168.0.10
  ## Defines the MasterNode IP
  # Please be aware, we only support x86_64 for the first node, ARM will NOT work by default
  MASTER1IP: 192.168.0.130
  # Defines the gateway for all nodes
  GATEWAY: 192.168.0.1
  # Defines the ip range metallb is allowed to use
  METALLB_RANGE: 192.168.0.11-192.168.0.99
  ##  IP's for NGINX, BLOCKY and DASHBOARD. Has to be within METALLB_RANGE and not in use
  # IP NGINX will use for exposing ingress-resources. Internal refers to LAN-only NGINX ingress, dont port-forward at router
  NGINX_INTERNAL_IP: 192.168.0.11
  # IP NGINX will use for exposing ingress-resources. Internal refers to LAN-and-WAN NGINX ingress, DO port-forward at router
  NGINX_EXTERNAL_IP: 192.168.0.12
  # IP Blocky DNS will be exposed on
  BLOCKY_IP: 192.168.0.13
  # Sets the Kubernetes Dashboard IP
  DASHBOARD_IP: 192.168.0.14
  ## Configures Traefik, ClusterIssuer and Blocky for said domain, using these credentials
  # domain is the base/highest level of your domain, so without subdomain, example: truecharts.org, not somesite.truecharts.org
  # To disable, please see the comments in their respective helm-values.yaml files!
  # When disabled, please use placeholder values instead.
  DOMAIN_0: cloudremuci.eu
  DOMAIN_0_EMAIL: remusd1998@proton.me
  DOMAIN_0_CLOUDFLARE_TOKEN: uT5QmxAsXmHz5AomDU93ytbCmB0VO_vw5Ybmfe8W
  # Used to automatically generate a sshkey-pair for FluxCD
  # Has to start with ssh://
  # Please make sure to NOT contain any special characters in the URL except "-"
  GITHUB_REPOSITORY: github.com:RemusDumitrascu/trueforge-config.git
  ## Uncomment and adapt to automatically setup your dockerhub credentials
  ## This should prevent much of the potential ratelimits
  # DOCKERHUB_USER: dockerhub-username
  # DOCKERHUB_PASSWORD: dockerhub-password
  ## DO NOT ALTER
  PODNET: 172.16.0.0/16
  SVCNET: 172.17.0.0/16
  ## My variables
  # General
  PROTONEMAIL: remusd1998@proton.me
  # R2
  R2_ACCESSKEY: a5349d444616976e93ff02124b0195ad
  VOLSYNC_ENCRKEY: FJMYAwd#^6*4sXjt
  R2_SECRET: 9520512393d88e25e0c06b6aab5cac38ca2261cbc08648cc7ccdb432dea207e4
  R2_URL: https://bcd62267e6af398d66c99217b84579fc.r2.cloudflarestorage.com
  CONFIG_TRUENAS_IP: 192.168.0.2
  MEDIA_NFS_PATH: /mnt/Main/Media
  
  CLUSTERNAME: main
