apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:ERWfN/FK2C3BVR0UHFxruEDRpnE1Ouw+zRlw+4QW7iNG4uYIzgc+AXBVWSKm3JyoHEZh0AyeAzTmrldQuuzLzM+EEtUba5KCxYuNwA8Qha/231//owgGCj/RvJ74Qpra4Db/FVJle6InPBsxxcW+F8/PURhOqfkwqFwgsi4zt58u2deCeTeaMXjrMCGM6UhFXD8OXvzXUGL6qpJyGdKRLem72TQV9tbSRWXDwx5OBMkihqdNRcD8l3kqz3UaYkJkNUYoqMCUPNSvQG55w/yjl144DKKJNKv8HcstFxB0EpHUJnPJkkWbzVsBe9vvLue3ZbKdc449ZZ8tCj2ex2Jry4QfLQhB2JScRMuqTzzgn7D0j81alB8TzyzQCGOSRra/,iv:IoTBKOWQs5QhBMax9QvTkOIAT3xyOB6UIJ5dvcyejJE=,tag:KsAWwWhp5c0vLgIOBAVNwQ==,type:str]
    identity.pub: ENC[AES256_GCM,data:pWIuMwtKkbN0ecsejRJSnw+irho0zP+6gJ3oYkzCLdyA9iSJdvhhwZnMqvhj8AAZj4DLIUEhs+Ena/RyGq2xbpbYMXEJlo9IyPhJYbZUQRZwn71s82Yfx0nJyAuXTFdeJNF2rxJRzD/i6Wmodl1JPNIlz6eZBcmOBPvK0aqiEnrARMDtBv6ysEFRjgRMabb7mVeQp4miAqq9MJI6McYesumHQnIBWI7zX0ouXVYp/rA62pWWFXjpUlJ0pVYOJ/arrAhJtAA3Qc2rRER0Uw==,iv:3Xx5YwXmotVX6SXSX6gPV7OFJM99SZvp9481xF8/220=,tag:mnMVUYC+TjMHqNDKwjg7xA==,type:str]
    known_hosts: ENC[AES256_GCM,data:3S/V8sthP1hR28lSLKMtz11fsv1Xog9LdG4KJ6Mv0RDaeplkHu1NXzNA8z27F4XAAB004KAU8q63Xw/yZWUVZyGzDX1Kca3FhxpnU2+TeH+YdXs1YBJG62CAOk7PQKOJYtpLFMHjA6numsj7Fzzo5Vaw8QgAX8rz7YTa1p1YRsskRC89QQSC8wGtrrV924bqV8SPhgdssTDpzNK1IiQJV4Q29ErJQf7dz8FO,iv:iAwG6bOBKLvXMaD+WHIz0LoqqlWjlJScCSGsnhPsuTg=,tag:gc5RR+S9qpdxAafWo4INlg==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age10tx0wzwnqyyefxheuu7s9wryt26h5hhvthvs8khaae2ackpwyp7s9lsd5r
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVRnN4NEI5WEFsbUpTZXpW
            R3NQVGltQ3h2OVRRN3NjblY3Wk5WcEFFc3k4CnkyM2I2YU9jSnFNTzlrV0EvRjNF
            YzJLM1hmZGxkUndBbE9MdWd6WnJkK2cKLS0tIGhGdTZGbUdtbjhQeUxubVhlQUJR
            QlMxb1R2bnZyK3o1bW1ZTHdVQ1drSmMKBXC/tpQVPpOtDI0EtgwycaxagF/gy1kh
            C16WW1NivtUTobG+OhvnggHP4nDpbMgToKETYLbaP1gGKMPzSC1IKg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-30T12:46:51Z"
    mac: ENC[AES256_GCM,data:ABtzOoGCemsUG7QcoLiSCX0WH6XeGChb64m4LIaw0sbNqQsmUWRh2GsMmWoKgmAf60oCuO6MlK5rJMRlMqSbbHAl0TkLC8nJRnIT0XjGNvZBuP2xjeGbdDRdCDP1MCrQl2uZGtWjshWhDAbqSLJm3eRgWLAWpbjIWmhN2//DFRg=,iv:DTjE6t5q5r530LwYhpZnWl+bPPYZZ540tp7nd7pTs1U=,tag:lfCqKB3Jubf/MCwuNnNF9w==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
