apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:GUr47t+vJuTUigczor1su+FKsnsMiRDSV27zek4Tvj8anh7cbrLsJku8m9KOssYYVp6jmB1yhDGa4LQmftOJ0/EYgsmOokfI1qLwJiwBeu7JLEo1Bu9louY+JHgTat+g0ygiRv30u6nJT18Tigk59XY+g6Q3U5qN0mplNY+VHM/jhlxrqa4ZTzicze8RjLYX69TjimxgARgQy8iotvypPbpmitTBsgCnWARiQnniZNgnj3ZGMOeecAv1PUenl9QAT3esid4ui9Ns6c9+JZ/96BqBlvtQiRVxD6PG41qGR8Wf1Oa373Yr4ocV06qY438jck9Lkus0x0owugsD0i9+znQgGPh4vjZI26p+8LnagwIHfRNq6XxN3sQrcSuR4pn4,iv:YYXUGoko6oIoCTMBgBTTGKJ2wbh7pzIEHznmvo8PHao=,tag:WkvCiXxNTsW5MLGq6fISuw==,type:str]
    identity.pub: ENC[AES256_GCM,data:CAEz0wTvgANQ4et6tNUoF4WDANuq+0cDjddyKBVa6CfiC7NJVQcTinEXcAKymh7MZ/aoluw8uCkNfg5P4A2uZnymciWRlqkWcjjQimzBxU5OTR8ou0qrnhfK+++e7sMNPvqhTluDlGFpRltvTHy5Pb9rzkPcAJViwMq5reMl7zrcMzl0RasMNYdEvBUPu22T+H7uC+rwhpmAaK1dd6daKJ11P9HEh/js6PGBJcsvTyDHQGJ0n59p7UOMymTufJAtnMTTs4F88uIQ9/KxYQ==,iv:d0QpO6RPHKxa4ScGtmggkYOwdv4ajQ3XuLVmUA92Ry4=,tag:9bkmFwy0ph0msbDiVLq5xw==,type:str]
    known_hosts: ENC[AES256_GCM,data:PWo3QbHBMUaLmhIRHuZp/WuKeY6QZXKrvG5HqOCFyEo/QknEryJl3GFTZbaLVnNniAIOw2+kedB0hsbZWOPr680EQHdGhF/4ed4zTLKpuvyHR+JU8eDkoamWXfgDSq8nh3KaaUGonPB8YDNmn/UloStRhiA8eSkBkibUydeXIKUfy/MY19PyYyo5i9L+gaPVmsh8TqkdEU/30iWOaBEwXzwESuTJH1OIad5S,iv:beIHBsHilgjtf9zmmOJrbT+5qqzpVJJeZSC4MSQuNvE=,tag:0+mahjucP5wqW9MUQptgNQ==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age10tx0wzwnqyyefxheuu7s9wryt26h5hhvthvs8khaae2ackpwyp7s9lsd5r
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmcUlCVi9CWjZXUG1BblFX
            ZUptQU8rdTZhNzQ5NWFsSFQzR1BGUi9vM0dVCmIxR2p3WVNVblkvSHdFQWFTTkVy
            bnVLSFBhZzNMNGhwYmtwYlBNY2tzbzAKLS0tIG9qUzl4MjRSMGs3VXJLVlpxcGZP
            Rm5EU1FFbTREbnI4RHl5aExyNVA1MUUKT4E88IbRvRaTOOzCRjB3/uZ7m7ze7u6f
            bjSS1qSyKrXbu/1DyMkQ5glVyHFvIfSgGZnT0urKZ+1NCXEQ0KUqFg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-30T10:42:07Z"
    mac: ENC[AES256_GCM,data:DCqqkrQ9CAbQRsSqP0G9FeDkBW0pmfiHgyu7LeCTGcT4gnXHzrfa0N8effU74GWk3QNGrEtqYlpFfDBdK6ou3O+qei7F30RRxZ5jgLTbAZ1ePwOy5T4YB3qzG0WbX7rvM81OSLzoCLrs868uLjFBMREdfDr5ckeQAgGNMEvwsfQ=,iv:c9XYnnTGOGXSaWkUe7/tVEy4ONvXF4VmMR0v/PydiJw=,tag:qwBQ8jNoGnkJ9PQ1il5ihQ==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
