apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:FLhtOaDSIQloLg5EzQprFq30qMx3IUOH0QLVtFFPOgJdKebXFwvJ53yQ02Jx9onWhk8hxQKUAcUhyd6GhbSk/HVnBemE1/MCdRdKa1xdL7bjHBpJRTtnpPC0c6ofJEE8pOzYhS/dZHYEdTbcPuT2hUkZ8kgdc2OuXwu2KKC44MAAiNuA0L8swtNJ1uVd3LP/3uh8csNmraqCCuDmkoTrZ3lLGuVBJmxEy1Y0qfOwBrzcg6fFJINZAIbpfms6s6KVG8nZPplrRjAM3e/tU7dNavzr5haQSLqJO/u1J8nOti51MaR7xS1c3umEbv23wvxMgeH7BI3N39r4X/pW2OKHJMzKjnAph84/RFI+Smw/W1O0GCVczBpSQzsDuyfINtPF,iv:1mSb8lj6OolJXZwh8tTdReUAOaGroDNCF3mfd7om9jI=,tag:FnWtXzxaznQRrxWAPhgyhg==,type:str]
    identity.pub: ENC[AES256_GCM,data:dS+4x3Z/bH/tjbBbei4wf6VxUR4hrtTF7B8s7V17StiULqVHTRo+b/sj/Mk/55nzqxH4rHrWQ2V5Hyzhru1jspIr0JWbfr2eN9xrnlyJD1D3/VVOMLtAnJhPrQMJntdVRFcHTs8FHjqL8YSBH6agmMCY+8IAXhdRMWYPx8Iq4vaoYxHHLWTGKmPjXNjC+ExWURjuoE6wZyBCvOKwf2TyfszRNhaUdmWZKbXpGY5P5X2eQTByZIWrAkbXHJBb0Dmn/S6wr2xEAIJO88m28g==,iv:PQLJLiKCu65HojzO+Nsh2ohUxuqs3I+hKPaKFdrBg5U=,tag:jHqK+I1teqRrogS3mP1F4g==,type:str]
    known_hosts: ENC[AES256_GCM,data:PQu3kLp1RtJguWW6zQX0irwSrNCpWh0lBrXDYglmA2jHI3OVohj/l3ELVd0LqZ2Pp0LqpMZKbnDtwd0yCkr0q9OpmWOtvYjGk/aya6GPYogBhgB14Sun3MRwt7nnsBo8paZhTA+fFU6ZLVRlFvt+AtEM0W9JPlAj5Hr2twG/QiMPriUkNOzJ5N5eze2ch64uwvVoCs4z+jbfONSkXG7KM9GwcWS02WrUaPvV,iv:LHqnbyImuf+gRJ9NRQwEN+1yB3m0D0HnswNHFEYJmX0=,tag:Q2rXuTqrQ9v07gxda9916g==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age10tx0wzwnqyyefxheuu7s9wryt26h5hhvthvs8khaae2ackpwyp7s9lsd5r
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuaGk1dVJFTk5UdTRsZjJL
            Z3QyUDVCMVNKWmRoVVZoN0lLTE42RXJadkhVCitaOHFobXowaGpEMGo0RlpIcE5w
            M3hWL2MzN1Z5dzNPNFNXSW0vU0I1QVkKLS0tIFdGMmRlUXdwWlI5b2VhcW9LdTkr
            WHJOcVBxb1Q0K1hzTDNwVjZQMlZJaE0KuNDKWhUbkVHB5x0zXFyPldkB08PQi/tu
            fc5NUaD1gWL5oZnCTzdYbXS3tNMhAt3mw+8KDCk2EKXgqmOhbwjLww==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-30T09:33:34Z"
    mac: ENC[AES256_GCM,data:6ODBNS5TlanQoWgu3wCJsTRhdfPu4/QuD/qhl1H0uWhAfP1XjWNMmN7ADCpODIN6AXgrO9pdbht7JRLyEILpsrcG0JMZS8l0ctrvKQVMvRgYE8IppDTC7V4iOk3wO4WZ4nQwMpK7mY+3+y+1Inu5J8KH9kEnyY/g6QAtWyEESmc=,iv:tZfViwjCf54UIGSQbcI8Nv+2wcPkLEzxpqwVILoqR40=,tag:PbDl9RwP1aK6shxB9j+9iA==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
