apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:oNbhUq3E6R4OIvSjzECWZzBixCLsczZAMMvYcg7hUoC66riGlWTXhpyKgXrenvgzfUavZqeG8M+oNmVjld3C6K30Z3vrPqvqNIRgTMyI4+jpQBojWdc5czxlNJ/UAnCqhqW2uqZuTjZAq3L7WmaC4TC0XxkAKh5SWdlr0WUchVFNeamvjE8kqSCkm1ziP9bBHQkycXeIkFaJbfC2tCxgiGinohhuRvmCF/BZt/BlJVtR9Gmo9UvTrJ47YMW5WfYa5cK2rXwa0Szmqf4PqJ9yMIxK9AlIAQ9PKLey92KNq9TpQrj4/TWEncgXohgrn7BdRsHVXmMf8E9Ag0Ltz4SAfEDTG9l8OXvTJPM99MgEB9cNa2cijy4ex5Ya+Zl+xMsl,iv:JRwfgsLNhNLNBPbNaNtYycLeRAJjDzGW1pMxW/47BMY=,tag:mF7HXUkMtwdfu50Khs3DIA==,type:str]
    identity.pub: ENC[AES256_GCM,data:0EIFwES/odP3eouaOMhiie/4jhUhHbGKxgWArhlQgc0VRWRjoj3DB4bGD/de91fC1w0x2EPRW0AJwzWCA3gd3YZz5IVB6HQnXM3X9TmytsIJp0I73x64ehCB142j/PANOqgO8jF9Py/we8wmom9V/s7O5lV5WYaUSWNqxjQ7d1ToSOIvIjTMDUBUtBSByLBoyt9xMN2byBIDvp+zapeEQ5zg8u0rCGRN8G3yaG/GCi8anc5E1uz/Z4z/Nfrh6DWK+3fr8z4atbKTV+6wVw==,iv:/WB0+hKJgdytpPP3F9FOFxlhcyKJyZqte8NPBoSZmVw=,tag:H3g/sbvn23FtZcps81wIqQ==,type:str]
    known_hosts: ENC[AES256_GCM,data:LmlG2vcbve7eKeIsysf+UlSEZuCnDQTSyQFDqoY3BVdsgBJ1QZLFCaYCOpCHrOQNOQ4fgiGbM6oQUoelyiFRhwRFSaTNx7A8dCxMGExzmSoOOd4z54nNJ3jgQ2tmGfo1J2zmKVFAiQjdG7AcrObTThZhOcWakIh4bYNMia+D9lWRymeMQuqHWh+Nuu+6LcifEYhXLu+zLyNWZ9aeNTGPlHy7Sg/CYCgGXdne,iv:KYekmdLZ6TkpL1geVpW/KeGqW+CQdpmwVaSgT2U2PDk=,tag:pNO7/kQRubz5D0pyieu2EA==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age10tx0wzwnqyyefxheuu7s9wryt26h5hhvthvs8khaae2ackpwyp7s9lsd5r
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBscXRiT1VhTmY5Z1g5YUpD
            NEx3dVNvSGlnWjFyQWhEM0plR1ZGZmxVeVdrCi9aUUErU0UreExsNHZWeUQ2TFcv
            RVlZTGkxR0Jmd1IycldzcGRnOUZGYUUKLS0tIDVtK2Q5Q1krQ0xPNHk5bnRndFNX
            Q2NwajJIRXlLMzBBY25NM3FUdGkybFEKV7SXBICpmerC3ff9uWIocnFdrX7v6qrQ
            CGJNWdVJPzdxrJLVXmCm9eJCfWXRi7wkJQNqhK8JjXV4drnAKnE5yQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-30T12:45:23Z"
    mac: ENC[AES256_GCM,data:fLdOc3UxazfUIvwQRPscUSRjJBfLS6L8W1mPA29oFUCWB+G/Eq1FSSe2taKPR2ENpqYMoNi6Bqw6sSTyMO33ybg9IeC6LVKzN6lmy2KJQSokViGpk1QkeZkuNMMNehu4Syfs3JdZjTqdm2i+p+x8IT1EPa7vG2kWgRmx7375tGQ=,iv:exggvMRY9kPygOLF3oDCdPsoBMIKzuSll+1FY+4z0L4=,tag:Z1yagQZaaxfDICuu3aTD0Q==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
