apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:SBKe8ilTglZ/PhueKXFdXhtcOE47jwGR+LFcHY92AnPcStvZkvgcu8MP6Kz5YXrwqV27bzaALnrWEHfCmiNvlSFLR/TeUcsUJ3/QdWUu7SRZNnPUPz2lblkiQMN4FnXc4qHcnCQ94gMU2YDvZ9aApjC1hJHp8aSNV3cRK50lARAuvrZmeCYfSFiZcZ4zx+KL79RUcK0hEcWpgnK44hc66kXNN3SUAZ3LozxK3u9fw7WboDM6Fi0XKlv9n620XNHgTQhQW39j0PLhKhljDeMScy+ImpswvT1j1xSt6Wh/cTSaxbOccF1093k+/OOvDNzsVc+e+XZ0CknXXnv6l/n6nafIEAL2fXWeacUBLfe2qB6xeJkPvHDmy6NTv2K1vact,iv:wGUGJZa/zuzR4zWnSCgvX0yJ3ZRCRXZNC6SHu8J2G1w=,tag:EPKhpwdCc3a2rVW8IUvkGQ==,type:str]
    identity.pub: ENC[AES256_GCM,data:9QROheTdJN6F0wwaEG88XX2bB9x8TxIpbKwJUlAZO92KKFL+KVnUiy4FUrbBhALihDVw6Wtl5gc9c2IFUd9HTmMKIf+JVjwmy19dtpXATivBIqqh7xbwG42oNIKmj2Ui85zvPK/W7J28Bb1tXlobuooKdeywa5oTCdVtzanuYald/LtIo0wsbiOWtnnO/MIZPwBlLk4wUfYPsCdtZU8MMty+T3QukRNPKYGmbZp/930NYxOEhi902tv9vNmD9P5WE54iPTwZS5c3l+iGjg==,iv:Rw+zzTwFcO5N6gESdWIXsrXRFmGSDC6moR488uY9IBw=,tag:yoRIVl40tQnUonZrTtpDdA==,type:str]
    known_hosts: ENC[AES256_GCM,data:0Eo9XBAfDqiWOqm7eA5PwG1eMgPCs+Y9bbykkujywNpvHyNxXX/gPONBsNjlMaAlh4NiBa3tWAtKTe8poX36mi1XibmYqjUUrGZJmW/c2H4ot4UCHYJ7MkfFm+khvwTPQ264XT7+xFrLNeKazpPnXmPxl2hWsMbAej3eS0NT+u+ih2ah+5dUlFU8XByBPNsTzbAiJhfXgsjc9ShPJNqH9DigGbrG7vH8vrYk,iv:pNyyvf1V068xcdzO/+jer+yxDSY4lgt37Rq9BuEqar0=,tag:sp+o1YSPSfbVts26ikTaUQ==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age10tx0wzwnqyyefxheuu7s9wryt26h5hhvthvs8khaae2ackpwyp7s9lsd5r
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHWjZGR3RieHdWTzU1d081
            ZG15R242Tjk2ZHpHbFRrY3FaanZkV3ljbzMwCi9vazBQTWZBOURva1ZPNEF1WWov
            UUw2OWg5VXh0VitzN1lFS3pveE9sbncKLS0tIHk3ZzJBNU9xUXhoMEp0UVpYUVBs
            ZlFHMVlEZHdmT0twTTRKRE9nY2RRbncKAjXfjwyDWRX6WGSjM/0ovqtjWVvIclNh
            yFk0JJu+X/MgQxboZ/hak8KE4bwH2E0LC4z7hdJPJt3g56VA5myYAw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-30T13:06:47Z"
    mac: ENC[AES256_GCM,data:laMNFYQ8YsAw4om+gxGgeYeJPZgm2OrWf54L3/0MZo3jAERadCk7Wm7aYh83RNCST/WDixbzAOiO5EkfenB/KmHY2jr08ujU6p5SseUCztTfmBnZ+E+0UzpcTc2Ew9Ya3/3A8ZzT7PCoc9miwpGCj9LR2pwfYjifKCFo3s+29Ro=,iv:AuukZIWWFc1hKFMm5z31X1IkknIR6xrjB2X0nwcbQ0M=,tag:H/ldL8jLGZD0C7nEBNsGnw==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
