apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:rLSblCaDbydluTk2oEmhibtqxM73Ooeigjt2KZZXZCMLSgw6sbnwczXXWx3IsuabPHfDLHs/CqOr3Yn6yPTGKODzGPWnAm+y+bKUzC4UnKpNCE53zAeXXDXPgAtKuxjqB7e5jPz7bO/oP7+CDX9m0iehHjnhpAOZnsjLJXKkEQD8bhSoGG56tfzszjYF663ius0m5S8AxwKh/f1Ka1EWPV381vWWf5NMC5RnD0fXHOWDWbePLeRxHJUhEqt0kftAe3gdK9A5PLdx5RHlbt1QxxzGbpiKLmd4KSwBKJWVFwcYLDviTrrrASDH6nkcEJsTolzWdtwGg5tyCwm8CBRw9CZ4Kjyo/VHsZW2PIHOXh5Xn4DSD7qjJy6INZJEnqL/Q,iv:k/vOsYgNcg8D1FPOH6N9v4WR47AzixjYjTY51AxRED0=,tag:7TaE5kyEhDzupDyQZCQbcw==,type:str]
    identity.pub: ENC[AES256_GCM,data:BDE5e8gOc9RIn0WV/mk4k7P1bJ+dmzbOjYpBfANPYb1R4mxE4RfdHpFu84jnhaMBgoSPw7zg8QN8AaXh02SdUQdok3pXTJBh5uElh9hu4jntRyju4sOfvNuriVsNULZPuXRLhPrQJwjBJRYsx/lQ/0VJz+egjp50GNnp2sJqgtc+A2hnf74VuzVgItD3YbbHxCCeBEYxUymW3z1u/pKdPZdaKJmDyOqaYbidW4RYHGoddZtRtLmzxWXJcaFZdrhOLMeiflS68b/yfQe3Yw==,iv:QKSUWyzKAygdwX6MocHi1iLn5X0QUt7ASA5+2vWWU1Q=,tag:cAbjmvLmCfYmD/VyrDaHSA==,type:str]
    known_hosts: ENC[AES256_GCM,data:y/45poeQequHTib03C3sppKQf0WB/8mkaYZ66lQrgGWGkm20rRYxMS7zf9cRl1AxVG+koSRiraG9tfy83myupKgP36Aid+6uZfNPpS1D9u5EH99sa+X3m87DqoJ7nVFCHFATPx6yBaxehLyKDbkzfqPNTEM0VmS75qF8yJcSDNIJOhVGeoeSk+fkG2hKIZeD4AV7KOyJ74MczuzxbEFkk7Iv7SrHBLraROcx,iv:iOTJgMnKpKxPVUzC/NyIvYXB+fRq3eUCYmFkEP7tbn8=,tag:lwKDBBAiZDF1Jh/GBHrhqw==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age10tx0wzwnqyyefxheuu7s9wryt26h5hhvthvs8khaae2ackpwyp7s9lsd5r
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqcHRsNWVUSVFrUkZVSW9l
            QkJCZHlXNElwUW85SksxNXNBU0NMQjdzVGtzClVrQWU4TkZwVENLTHBKdmVPSWFz
            OUpmT2pSM0lJYlRwb1hkR3BrSU5Xek0KLS0tIFM2RVAwZFJJWUYrajV6WEpPS1RG
            N0cwOFIwRWZkNURBZ2tTNTc0aEk2ZkkKRR7VMFTwIdUjSnUzi0eCD5jHv0mtOCxb
            afPSyNTqwXXcewqicI3A+UCVfn1ALtZOolq9IxXrlB0DUaDIeruyvw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-30T11:52:38Z"
    mac: ENC[AES256_GCM,data:EbkcemJTcJsFsNrINXrSUDnxx9+balEPwuapXSAQGAaDmp+SZR+0eDt3XslceowKqZxvQDYT4nK3r67AJfqErnil8c6U4taI2n9cf7d9ssEHu+stNNCj4S86MtmuCE06WGPtSJYIHnJFkocRlTxsal3gMW+2t6PI0rFjYbW7GYw=,iv:UKZgOu4oWJN9cIxbRsbS5LwW3UxaehmDQS0m8CUJBcs=,tag:aPUQE/hbmDriQ0lCFKbZrA==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
