apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: |
        -----BEGIN EC PRIVATE KEY-----
        MIGkAgEBBDDf0UvzXWNwTY1mK33jFsb5ujyYXMJMv3b+js+ckyZdGd60arYgqzPR
        AgU1jV1cDfegBwYFK4EEACKhZANiAAQyz0q4BboW01XiaNQXsjyAI9zQDQQwLkir
        Ayn4Qz3Xp0WcTtzJDxgjiFBH43g2rCv3sZp+CXtcANh/I8muRd+zO5NU5oL6s5/1
        6pWIT6ZsrfSy9HjmkLQ3LI4GSQ1B+Ws=
        -----END EC PRIVATE KEY-----
    identity.pub: |
        ecdsa-sha2-nistp384 AAAAE2VjZHNhLXNoYTItbmlzdHAzODQAAAAIbmlzdHAzODQAAABhBDLPSrgFuhbTVeJo1BeyPIAj3NANBDAuSKsDKfhDPdenRZxO3MkPGCOIUEfjeDasK/exmn4Je1wA2H8jya5F37M7k1Tmgvqzn/XqlYhPpmyt9LL0eOaQtDcsjgZJDUH5aw==
    known_hosts: github.com ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBEmKSENjQEezOmxkZMy7opKgwFB9nkt5YRrYMjNuG5N87uRgg6CLrbo5wAdT/y6v0mKV0U2w0WZ2YB/++Tpockg=
type: Opaque
