apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:vcmxK8CLmu48wZQwQKvmFFDRHdBIc3oGF608ICbJIlNxCyBycPNDd7B4LUC4vCRWPwt00Y7G1XnXfpNjFv5fPjU9OW7fLnO/8WyW4/Bp5iEqkhzoVc9dEUKPLvudaohkszWMYjkFvrrZZwRIvtMizWam0YII/CAQu+an17ndaad3y/RCQQDKWorgQ+sO4in/fY5kKOgXbAleK2Z1Psc2hXH0hjXr6zcVR2gOPj7oqwzbPN4OkQlEPszuouC2vNn4u0BX9GYYaHjNtw7AfgPKbTLVEQWisChUPy3272u2GgOkH60TOoPacA2h2TKfhIyL77v/Dz3IqzbncZNLWqLRrrPwhtdFPmtjlzKZWzbDtT7vH+E7M8W1cVJtSDTZufnD,iv:kvd5BUHrvlox0pdWfTKrbrahL++3621HAK53sT63HtU=,tag:rg3g+l6e/Qe9ekJ+5oq8UQ==,type:str]
    identity.pub: ENC[AES256_GCM,data:8yOcNg/LjawONoFJIkD9M/vCbxC15JwrT8FJH8Wb4pPcyGUvN1/d++Ao7P4HBwSWvtnRe2wpnKeDF5fuxrHOX6WKxuZKxmLzHWGcCOIRuDryuCG+C1dp82z2ximBObmyUqiaxNbGXGkj/zYNgVVfhJ4Vglp6zA+IKckKnx6+8lSVdoBY1TRj5H/k91nj264lh+K/Aio8pRC+ODWtBzwjenwLnYL+fQLxmjSrvpFJJezcAcYyZdKF++bbO5qCY5O6GlrpUl4BSDfkKvRrsA==,iv:ssc9MvNLb59Gq+gNql9LBmRD0TSi+l1PVHEyCKxiEjc=,tag:gNNs3h1VoYO/5RLrgwTm+g==,type:str]
    known_hosts: ENC[AES256_GCM,data:8lh11xw7uOy6VQ+CzEFUvgbraB27Q/nbQpF6rm/yFMf/fG3UviGA0iUtLXDbs5l2H1GhFK5X8W0SY02p1p1mNHZGUz56PRdgynacq7iBuSX4LTkkeLsf+/xoPXFCkQu9IDxSLzvRJd0+qb92+5TTPBNbcdbutVY0zXmYMZUBd8x+880DCol/k/sMTuvbaNeNj2Np0YTT49uFCRf1nzdbxiPkxNt00xOwvAtc,iv:884tsc5yn0Pns38731MRogCg2VdmpNsfBYwaff8Y2+A=,tag:12Xl3/D38v/ExnY+oZ2ERA==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age10tx0wzwnqyyefxheuu7s9wryt26h5hhvthvs8khaae2ackpwyp7s9lsd5r
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaZHc2dm5vcVhSWVBkUVZD
            VGZZY2R0WmtuMUFSM2tPdy82NmwveTNKS2gwCmc2ekszRGdsQ2tGbzB5Y25wTjIr
            NitWbTR5TzNyZWowWkY2U1RPV0s5cXcKLS0tIHlydE1wemxoaUVsUXVxSUh0Zm9T
            YTJUZER0VTVDQzQzTEdNZTRBa3lHL2cKicrAXu9qd5I5ivsnLxlKA/uEiPgdNYZo
            4s7me8ahfTGwaXCw3xZMukqhIQXYCyJ/mXEO6PebxGqPvioM6l1gCA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-30T13:27:33Z"
    mac: ENC[AES256_GCM,data:Ei6Q72wnELNDXfKlIpNmR9kyG19m2lX1i7R2ciswER0KiozNVHf8jRzMQNYslFil9B1yFDboRTHWfVbLk6GFEx+gUEnrsacFQMiERP4SNuyT0HUFki+010IVAZmKzFF7CkGuFBvu9oQtsSyt6Epo0hKpY/6npXXe79gnVfNZDog=,iv:pLY3meRjqL4xLHwz9wbE857ckeKyACpjklvlNZaAPss=,tag:1weAgjTXq8xocRhndfetAQ==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
