apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:3K9A0mKleNMetHQfh8AneGYTAXMDx9AwYy1Sh6F+prAOkvXdozeilLex9Ip1nVboqzdvZZuWKlW0Yr4BmY2wjrEwBz8lnD+eRWECQa2VTW99OPMig3HcBfsTcOeT+92yLv8pKi5e3UCyVSpzHoNTnsxaY+WTLoGJT8mSZxXxL2wIG3Fpqk3U5YtbKUvVxwInE79dcJ5ZiRVtppow6yA8DhtOcmqpaHqWL/klPDRg2BjRb9pHxaRhygI5yFvshjcBv6ONdf/lmKiALLu9IO2+DEx1DfMiMBmAMpUZN3l0q2nc/vh5equUlILNLuepBsTRmauBvyvcJrvDMPl2dE8gQVnATa4jV2D8/kfdQCET5IzxobFAJmDckIKC9+XJQ3Ru,iv:rgdRpE0q2z2LizgOrYY8buUloPCB5K2H16FJnJRCR9M=,tag:wlb4xZv/43sZOAC/a1h6ZA==,type:str]
    identity.pub: ENC[AES256_GCM,data:K6WInDOaEqYTztSpm8zKrm4d4FbuqZLw2m01glZ8nSlp5t4tS3yQtErsZR2ryNH6yf0BKIj1kq8Eut4cgBWMh5FDfPfhQrphsi79Ne0bEi3LZg3XgtTv9AbZeC5TSxVdYkq4EDgSBCmBGNKit/5HN65p26tZnujYtCCXzv8ore7czSm1me+TCKMsPQELicHCSbWymRbEeV7qpFyCic06aW4LzKtds7D7q/96Aqh6u8ppmLrZkL/ZLPbp1/RXlBCtXnlaW8+gSxi8Vj3E9A==,iv:ifJK0oGxI95PM1dnSV2Vh03kZutiEdu+6JD8KZ2qxM4=,tag:F/kdUr6EfagJZFaRcDV8FQ==,type:str]
    known_hosts: ENC[AES256_GCM,data:hjmAASrcfLV5GhP7J4CWb93vxzXqntzCaCe3w5yaZatPun2bpSbRekB03/5RJ642iHqox7pyZGGbEDyTz0XyrXz/uqO7h+kOr+lIXZF8IPai59ZwpaJYEKlQe0ZBznSl/IIjV3olqfbFkkz0+ufIa+qgMx3cQkePVJ2cX8m2OxWlM6qL+gMh1oX4O9WSKQLWii6cHIUqiyD4ZXDZ9P0USjpP8dWm/+BCVqbU,iv:+d36feiGvua+RT+dY4UcdQnEnyHjx/9fFvl+90GZcaQ=,tag:klEPPNmjSSvxErFzn+qrKA==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age10tx0wzwnqyyefxheuu7s9wryt26h5hhvthvs8khaae2ackpwyp7s9lsd5r
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMTDNKVzNWT1VSMEhuM1Z4
            T3pIOW01U3RhYWxNNEtXbDBnTjlyNjNIMnlBCnRaWm1TRXk5VHpZemNJR205MEY4
            b0xtdU9XbE1ta2pXcDYvZjF0VlNKWUkKLS0tIDlmazNvblh3bDl1Y28xcGNsQndJ
            TnA2akxvVDRMUzY0eFBWOFdJSWtBM0UKWtzP9PwivdhLZKQE1D4UEKuGFrxLWunD
            1vl8d9cex4YX0TVyTwOooTYx+jAHhS30mv40yuLRzQ8sqhK7xAJ3xA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-29T15:25:37Z"
    mac: ENC[AES256_GCM,data:8Tmd7Ox0BAq/OO3ZWcUaxdh8bvPPrQpq2CSyA8MCVnFtqtQcSUZX62lnspjzveCHs2WACxHwGc/0QUruwiCd/SHj/JqwYCAKLtMFgd/+GGWjaDcvY4E3/AxLD7eQick4hczawEOh+CU3aeoSIaQFmRj/rQKCGh8KV2eW5dYU4Ds=,iv:VcbDhlOgvbzov71ESpYihveZfB6JaL4PA055OU88lhQ=,tag:+Q4U6O2Gc2+RDlWaFNZBOw==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
