apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:N8MXeMFNHas/SuCUh7s+0aqODBxRhtCue+6fOBl71Pe+FCcToqJFsud8KcFsX2hqsUr9TITDBFfQroVWF8vkrmUIvszL8lr9FtdPjQQfoEGhREXWH/eMiuCrDYPjaRqTBTxQkLmYLa9yC+87i7/oDZ9qLxZJ9WSyEhfAqQgBEZVVzAcgK14UpPdbiJuMIl6TaIlAcifEzd/yPmLiUaFNuMRLeVaZJEnoay36YmhPZQ15ihMYRMtPc+x1fQtz2fyzBnmjuR1tVkjPex4xUFrXiPoGCjDPmB6B+p+Bq3sHpRKhNQpjV+0b792vG2GHdq8ndugDrQ+9/1PYeSX5dRt5XK/jaj/IgtXq4YGHIbzSM7fnZG8ypwVhiNgggeqMrN64,iv:2/oWhaBoB+Oo8iufDrOR7ha6iJkIEQ35sC8jvpDg8FU=,tag:oI4OU/TuEaXeqKvRnQQlQg==,type:str]
    identity.pub: ENC[AES256_GCM,data:Rhdd+KYw/7rug5tz9BsR34gtVEaK/mqKXHGymCih+k9aCafn5I8/6OhET27lTI0i5lSLwYZVNlEAX+LavDHi6NvxxpmvNOFdxEbI+Ml/+WTzZ1bcmGyRk6dif+DbXL5aLxUhkLCpEW0PVnStiTad91h5DLiXWVnVFukyPHUBVCpxxyDsCayqWgXBsfWoU2gYzaGb17zHAbHt+fGsfNN9AVBfJutyuhEStysacVsim5Tr8VCV8/opnV/9fWqHZYU87uWGkhICb+zhITFLwQ==,iv:qTw4laiw5fiAeS2NDylBQborJIXpWY60xQha/VKRo0M=,tag:Mrc85Hcm0JDTJ1UgtKup3g==,type:str]
    known_hosts: ENC[AES256_GCM,data:kxRKBD+OlZaQp+TlFtmnyCOIJ0/e/bJgHOYfj4L+wX35yDWPWMpNGpDgSdirfi1m0lpmjUbug9Vv9kq6dXmn+KyIpCXck115rNOFxnn/Sclnpw7T7VKhSXy989EzMEgdFisGMiTcHLkBl9shNuklAdN4xpJYK2L0VIt5c7BWpCxZMCXysgsomwe3uSM8idwhKhY2KKxDlwToZvRvALvOr/3OtmvtGDhtbdU/,iv:M8qWvoUqYV184GlDeZUngHBpmCJyFliH2gw3/oGio6U=,tag:tPP1Lgil+Vrq7ibqpCQCGg==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age10tx0wzwnqyyefxheuu7s9wryt26h5hhvthvs8khaae2ackpwyp7s9lsd5r
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6Tk05bjdDOTZxelVqaWdC
            azYvczRGRGdvSXM3WmJRZVpRQ3ZiZFE3WlVrCmlpYVJnMkVNYnFwd25vSi9rWlFk
            ZGhQcW1UV3ZMU2NTd0Y3SEFzeEZ2WXcKLS0tIEtPMVBkb0pPR2lpejBLS0dZL09Z
            eDlNTGpENGl2bEtOMG1zNUllTjc2MGMKhfqwc7qzBZRPUvCJJ8BUrz9WTvxldc6C
            W8BzTUw8/V1qUHsyEsNuDyXthEj+BNhKCuVD7ycbJA58lhh8s2u9CA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-30T14:06:54Z"
    mac: ENC[AES256_GCM,data:pdgpppoJ41MOfxQkNA2RT0ekiTphGf+d/QL+TnqLEPsP9V8fFjMdIzvwjqUHuM5Hv7+AKvWAyzAgG8t/zKSy3DSDBy5ho0tKPGVic8qOY3M5lSTvAeHSLXHqoMk9uJ5YB0c8zxTdxa6UJzfBsPJlS1fcJ/bEDZWSI3/jP+3UDPs=,iv:zwkS1xllquQZEiP/A4l8WGoLlIgiwGRkCo5aIgK3goU=,tag:ag0YJycgycne2DNu6a9lWQ==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
