apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:Cp8ucGuM9fIY4KIyhArIScyxEhRgu9yIWiIGKfTZpoN4bSL+Fu01kSJ6ucgmYx9dfRTOlxrr7BLdwqSrK1Ukn7V6FGD0A/Vs0p+N82J/lsrpIerkyf1Fv9KKaNgHYchAB84sHh4fklsmP36yMITsLOgAePEkX9Y0pxEy4Cqp9XBGd/BmSp0iM9N6S1IWvkJt12niahjUQQPi+GR4byRzwxlh8vpNE+9sX0Kb4ocCW47TyQV124EKv7O2ICRUHA0m0IRYEBYsv6EcHEeO5LK8FAsNZHpIpuPBhZlr0lPNdkqo25HgtDU/VHWRewfquGqq9Lv9vq2BvmGVMPRJmRbdDmfos8DIwJmuy744N41FxSa5X0p28K2xSkwtVrK4Lxhq,iv:WflfKXJgQJMdqFyfeM7MG2OL5KsiBopSELcpnfgdU8A=,tag:OWHxhMLdVJoc5brPlhBcSg==,type:str]
    identity.pub: ENC[AES256_GCM,data:jUdRd2umL9NH8q4GePNfSlehXpDzpWZfahIoHAk50P9L7zcmSZkVgONN+gs2OdVUQLTtuSkXNyRx+YKXgfCcNWKe67TG1qwKTbQ6PL/douXJqLKlMwb6LT1SgIA9y6uCxDlF49krlfwlHzdNJ7EkoqKknp8PY1+kfLARNGxv81h8Ick/V30379o1rONoqKVua6iS33la9ywBfLzauGecLsQMJfeVFL1nJO6VSxp+W76k6Q1dvrauchYjRlxW52Kv16eEIGI1S0nuguJZAA==,iv:HR9T5hq8bhOB2xvXmqrGn3zkAfbEwuJHVV4ZAOd/b6E=,tag:QKqG42+ThiMDlg6bNRwYKQ==,type:str]
    known_hosts: ENC[AES256_GCM,data:8naL2VNVcRWHyOGA52avvYXBYc1y0uctHtGxiJZJEuOb9pprVvpOeqzZ9bgVyu8IpI4zQV45u5SDYzbOojLThKNcKp4hKglLkDpMXCmTJd4uGK9APuOKQyzQu2ChznqERFP2nZX4GH7EczpWf7EombSq/3H9PeCaVnIkp2t8L3FQpWOjw21sUE6JMxqAiWRc5L7b6vWYNkNwEKyF/Er0yOcVOL8qwLdRcivy,iv:ssCLEcjjz5wJEXiBGykfAaZynnWvyNe5mfZyzw0+kZI=,tag:Vmt+Rf4CKD0hkIHR7ChoIQ==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age10tx0wzwnqyyefxheuu7s9wryt26h5hhvthvs8khaae2ackpwyp7s9lsd5r
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsS0YzY2tZNWl2ZlBoQkxw
            dVptS3g0ZHBrSGZ2Y3crNmdKMjBGQ09OWjBzCmlxZ3JrM1RMYzhwUkxxOUdZcW5t
            NEJoMmFCamJUYjU2dG1INFR5a1hhcWsKLS0tIEpPY1JyYzFwM3lCRU5lSW9PR1FK
            dGp2SlpnZStaS3REVmRuUjVLdkRVMTgKk9k2eZizMtJFu5N6C30CyORP1pZEJy4a
            LtB1dXA6b5OgWKM0xfK2AZqMRaTJvhG2U7pzIWFjvsSGnzev/z/Rng==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-30T11:13:46Z"
    mac: ENC[AES256_GCM,data:iu+ZUs5gvG9fuArpVkyWUsHz5Gvs4ES3AbQI5j6efsXaTPNMOX23hnu70t9KMG82ELhfBF28oHlf2ywhPmajP4YumuilFubUcr4ZYCipF1A5+r99ylLanNEATz39Fkjs6u+pXrpdUtx1hD5nDPhd8zJaXd1FCZeRNx2WKXO73Tc=,iv:262cR6F+eq2DOK7PjqWz4xsvVn9GTSq0vQ8viPzSZ+c=,tag:U1ayhtj1djZmcHJPpfT3KA==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
