apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:sMhL1QPcpwdE9Mp/EuPuBPievCS8aHYvuxJbk4gEC1e9hFRyIDtaiqlvS36Lcw+hM77FyXSqB8gab+oSzGbOEKE2DaimIJPfjJh/IW5O0PeK7oqouvVAlnpgNcGPDYLafgwJVFlF5HVGsjVPeOHtzUxsY69tAKXYHakea6o86hqY+HEm1eAJuqESxVRJL59MLnUJtkWtAfV2qW3wPNdqn+dUTOXBsycUUkeDdHlEQ3nyO8JFnbA1Vs1K+RkeINsQ3j+vSFBf7PfCXD1vUxyiaCIrlTouDYh5VGiH7nCQvlvf3yH/nQHaOKMxhNiqtr44D+gdO0aEdh3efVhoWup8Up+H76XqVtimNBl7zSYm1reQBQq+l/CHp8OknOgwZ3qZ,iv:ZAPqcDVjAO2d8CrHEMABVgRTsVrszDpKx2aBi2KDVNs=,tag:tXQAnhj16B56L297006Tgg==,type:str]
    identity.pub: ENC[AES256_GCM,data:UZg8xZyX3J3VqvTXA1eBljGs0mW5gqpOdpyVtKS2g2VMj1mLH4p6SYHQZcEXy3zeG48sg7AGaD2zKZIu37icAxp2ayo07NnIADMUtMpP+3qtttTh0Z1iocoVsi8eFtKLuLB9tqRrlxxBsIkdLaUfegz2/En121StOOifk/NYS0lB4aCW4Q+6ailRvZyT/UJ82eOgFEePXYOqNVfOfdFKlIUG4osThCrkY6Grgz2vr7r6uCTfxuisb7YW3lM/Q4bgi6ZRMc/V1+ap11C18g==,iv:cyRWaWwiVvDu+A16Pm+O3GnibPrhnOZuvHBISLuBN04=,tag:2A9UFZH9A4+H2o2OiaKH7Q==,type:str]
    known_hosts: ENC[AES256_GCM,data:INftZcDex8iidgcYYr0q1YAo+W4defs/bGFb71AWe6MvIj5ivpD+uCdU3R30uDRDSAFSV9wtN9JMnjs/1nwsh2f1ris/+g3FHE3Qaub9Jd6f64zWZuAxiX7ho3WZevwWzFm1jvBxTN3Y+uMGHIb0/NLaCamu286aWiEIHaQr3KMahKtKStb+sVRVfusLb9aYz0SarI+cwQ/tpT7KCiM4MtbgREpAMpYtzl43,iv:XTfnGAhPuRVVYdDRYFPXkqu9MOpajJGl8T8A1xYt2KM=,tag:6RAeNmAPlZWyJO2jmRfKag==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age10tx0wzwnqyyefxheuu7s9wryt26h5hhvthvs8khaae2ackpwyp7s9lsd5r
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCdlJHYjJSWEl2SHg0QmJz
            eHluUWVPRjRBQ0NiUmhGVFVuenN2aEZiMkhNCmtiY2FVVzkzcjcvZDI2Q3lhYTNE
            K3dRb1dlNGtZK1diY2dZQ0VYTFN4cHcKLS0tIElHZndQVGVSUEUzTUxvd2ZqUlRo
            L3E4L0NMNjl2dnQ5ZG5ORklrb1BHTjAKHYGdRsI30BeoZyXHT4pOScIsiiC85Bia
            8ExZBV6fQiAuxcZJRGL5eDL50gNR1K5SjqJkWyLbuQbzF/EHQvLzcA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-30T08:54:31Z"
    mac: ENC[AES256_GCM,data:r5JlxSdpX9klcdAHT8d08CWWDn/u9YQXKau6/HL/PoGgULz0zFAv0c2TRCWBiQbUKRakMXe91DSIVooLkfgn7cJMVWGzS6xiqpNqkiVzwY9N2T9N7f8t9EAYvP8y2Y2Oe+gvXVoF7ybx9eWX6b2uVmvPA0qP+mWHDpwjHb2kta8=,iv:4CilC6/SwkbTtWTdFIawvrrw9o6/JP5/5ogZZni3dmw=,tag:GnqBoXh8Y16oHFwxQRx3bw==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
